safe: false
source: .
destination: ./_site
lsi: false
pygments: true

url: https://zgaur.in
title: Gaurav Chaudhary
description: 'Developer'
permalink: /blog/:title.html

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

paginate: 2

gems: 
  - jekyll-mermaid
  - jekyll-paginate-v2

mermaid:
  src: '/js/mermaid.js'
  src_config: '/js/mermaid_config.js'

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true