safe: false
source: .
destination: ./_site
lsi: false
pygments: true

url: https://zgaur.in
title: Gaurav Chaudhary
description: 'Developer'
permalink: /blog/:title.html

markdown: kramdown
kramdown:
    math_engine: mathjax


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-youtube

gems: 
  - jekyll-mermaid
  - jekyll-paginate-v2

mermaid:
  src: '/js/mermaid.js'
  src_config: '/js/mermaid_config.js'



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true